name: cdk_diff_manual

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'branch (from wallet-frontend repo code)'
        required: true
      stack: 
        description: 'stack (dev uat madhouse)'
        required: true
      commit: 
        description: 'commit (the specific commit that we would like to build)'
        required: false

env:
  DEV_BRANCH: ${{github.event.inputs.branch}}
  STACK: ${{github.event.inputs.stack}}
  COMMIT: ${{github.event.inputs.commit}}

jobs:
  print_env_vars:
    runs-on: ubuntu-latest
    steps:
    - name: Print env variables
      run: echo env variables DEV_BRANCH ${{ env.DEV_BRANCH }} STACK ${{ env.STACK }} COMMIT ${{ env.COMMIT }}
  
  docker_build:
    runs-on: ubuntu-latest
    environment: cdk-dev-deploy
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory:  src/docker/
      run:  docker build --build-arg BRANCH=${{ env.DEV_BRANCH }} --build-arg COMMIT=${{ env.COMMIT }} -t wallet-frontend . --file Dockerfile

  cdk_diff:    
    runs-on: ubuntu-latest
    environment: cdk-dev-deploy
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run:  cd src/ && npm install && npm run build 
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: src/
          cdk_stack: ${{ env.STACK }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'
          