name: cdk_diff_manual

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'branch (from wallet-frontend repo code)'
        required: true
      stack: 
        description: 'stack (dev uat madhouse)'
        required: true

env:
  DEV_BRANCH: ${{github.event.inputs.branch}}
  STACK: ${{github.event.inputs.stack}}

jobs:
  docker_build:
    runs-on: ubuntu-latest
    environment: cdk-dev-deploy
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory:  src/docker/
      run:  docker build --build-arg BRANCH=${{ env.DEV_BRANCH }} -t wallet-frontend . --file Dockerfile

  cdk_diff:    
    runs-on: ubuntu-latest
    environment: cdk-dev-deploy
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run:  cd src/ && npm install && npm run build 
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: src/
          cdk_stack: ${{ env.STACK }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'
          