name: cdk_deploy_staging

on:
  workflow_dispatch:
    inputs:
      commit: 
        description: 'commit (the specific commit that we would like to build)'
        required: false
      branch: 
        description: 'branch (from wallet-frontend repo code)'
        required: true

env:
  COMMIT: ${{github.event.inputs.commit}}
  DEV_BRANCH: ${{github.event.inputs.branch}}
  STACK: uat
  NEXT_PUBLIC_AWS_S3_ACCESS_KEY: ${{secrets.NEXT_PUBLIC_AWS_S3_ACCESS_KEY}}
  NEXT_PUBLIC_AWS_S3_REGION: ${{vars.NEXT_PUBLIC_AWS_S3_REGION}}
  NEXT_PUBLIC_AWS_S3_SECRET_KEY: ${{secrets.NEXT_PUBLIC_AWS_S3_SECRET_KEY}}
  NEXT_PUBLIC_EMAIL: ${{vars.NEXT_PUBLIC_EMAIL}}

jobs:
  print_env_vars:
    runs-on: ubuntu-latest
    environment: cdk-deploy
    steps:
    - name: Print env variables
      run: echo env variables DEV_BRANCH ${{ env.DEV_BRANCH }} STACK ${{ env.STACK }} COMMIT ${{ env.COMMIT }}

  cdk_deploy:    
    runs-on: ubuntu-latest
    environment: cdk-deploy
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run:  cd src/ && npm install && npm run build 
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: src/
          cdk_stack: ${{ env.STACK }} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'
        
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        if: github.ref == 'refs/heads/main'
        with:
          cdk_subcommand: 'deploy'
          working_dir: ./src
          cdk_stack: ${{ env.STACK }} 
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'
