name: manual_deploy

on:
  workflow_dispatch:

jobs:
  cdk_deploy:    
    runs-on: ubuntu-latest
    steps: 
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ github.event.inputs.stack }}
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'
